title: 'Meow Squabble'
default_lang: en
author:
  name: 'Meow Squabble'
  email: meow@dpera.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Meow Squabble sets out to make a tennis tool to help professionals track their statistics and improve the game.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
